FROM node:14.5.0-alpine

ENV PORT 3000

# Install git for ui and internal packages
RUN apk add --no-cache git

# Set app directory
WORKDIR /app

# build occurs on pipeline

# Copying source files
ADD dist /app/dist

EXPOSE ${PORT}

ENTRYPOINT ["./bin/docker_run.sh"]
