FROM node:23-alpine

ARG PORT
ARG NEXT_PUBLIC_GRAPHQL_WS
ARG NEXT_PUBLIC_GRAPHQL_URL
ARG NEXT_PUBLIC_RPC_WEBSOCKET
ARG NEXT_PUBLIC_CHAIN_TYPE
ARG NODE_ENV
ARG PRICE_API_URL
ARG PRICE_API_KEY
ENV PORT $PORT
ENV NEXT_PUBLIC_GRAPHQL_WS $NEXT_PUBLIC_GRAPHQL_WS
ENV NEXT_PUBLIC_GRAPHQL_URL $NEXT_PUBLIC_GRAPHQL_URL
ENV NEXT_PUBLIC_RPC_WEBSOCKET $NEXT_PUBLIC_RPC_WEBSOCKET
ENV NEXT_PUBLIC_CHAIN_TYPE $NEXT_PUBLIC_CHAIN_TYPE
ENV NODE_ENV $NODE_ENV
ENV PRICE_API_URL $PRICE_API_URL
ENV PRICE_API_KEY $PRICE_API_KEY

# Install git for ui and internal packages
RUN apk add --no-cache git

# Set app directory
WORKDIR /app

# Installing dependencies
COPY package*.json ./
RUN mkdir node_modules
RUN npm ci
RUN npx browserslist@latest --update-db

# Copying source files
COPY . .

RUN npm run build:next
EXPOSE ${PORT}
ENTRYPOINT ["./bin/docker_run.sh"]