query GetMessagesByAddressExport(
  $address: _text
  $limit: bigint = 50
  $offset: bigint = 0
  $types: _text = "{}"
  $startDate: timestamp
  $endDate: timestamp
) {
  messagesByAddress: messages_by_address(
    args: {addresses: $address, types: $types, limit: $limit, offset: $offset}
    where: {transaction: {block: {timestamp: {_gte: $startDate, _lte: $endDate}}}}
    order_by: {height: desc}
  ) {
    transaction {
      height
      hash
      success
      messages
      logs
      fee
      gasUsed: gas_used
      gasWanted: gas_wanted
      rawLog: raw_log
      block {
        height
        timestamp
      }
    }
  }
}

