query GetMessagesByAddressExport($address: _text, $limit: Int = 1000, $offset: Int = 0, $types: _text = "{}", $where: message_bool_exp = {}) {
  messagesByAddress: messages_by_address(
    args: {addresses: $address, types: $types, limit: 100000, offset: 0}
    where: $where
    limit: $limit
    offset: $offset
    order_by: [{height: desc}, {transaction_hash: asc}, {index: asc}]
  ) {
    transaction {
      height
      hash
      success
      messages
      logs
      fee
      gasUsed: gas_used
      gasWanted: gas_wanted
      rawLog: raw_log
      block {
        height
        timestamp
      }
    }
  }
}
