
subscription LastHundredBlocks($address: String) {
  block(offset: 1, order_by: {height: desc}, limit: 100) {
    height
    validator {
      validatorInfo: validator_info {
        operatorAddress: operator_address
      }
    }
    transactions {
    	hash
  	}
    precommits: pre_commits(where: {validator: {validator_info: {operator_address: {_eq: $address}}}}) {
      validatorAddress: validator_address
    }
  }
}

subscription ValidatorLastSeenListener($address: String) {
  preCommit: pre_commit(limit: 1, where: {validator: {validator_info: {operator_address: {_eq: $address}}}}, order_by: {height: desc}) {
    height
    timestamp
  }
}

query ValidatorDescription($address: String) {
  validator(where: {validator_info: {operator_address: {_eq: $address}}}) {
    validatorDescriptions: validator_descriptions(order_by: {height: desc}, limit: 1) {
      details
      website
    }
  }
}

query ValidatorStatuses($address: String) {
  validator(where: {validator_info: {operator_address: {_eq: $address}}}) {
    validatorStatuses: validator_statuses(order_by: {height: desc}, limit: 1) {
      status
      jailed
      height
    }
  }
  slashingParams: slashing_params(order_by: {height: desc}, limit: 1) {
    params
  }
}

query ValidatorSigningInfos($address: String) {
  validator(where: {validator_info: {operator_address: {_eq: $address}}}) {
    validatorSigningInfos: validator_signing_infos(order_by: {height: desc}, limit: 1) {
      missedBlocksCounter: missed_blocks_counter
      tombstoned
    }
  }
}

query ValidatorInfo($address: String, $delegatorAddress: String) {
  validator_denom(where: {validator: {validator_info: {operator_address: {_eq: $address}}}}) {
    denom
    validator {
      validatorInfo: validator_info {
        operatorAddress: operator_address
        selfDelegateAddress: self_delegate_address
        maxRate: max_rate
      }
      validatorDescriptions: validator_descriptions(order_by: {height: desc}, limit: 1) {
        details
        website
      }
      validatorStatuses: validator_statuses(order_by: {height: desc}, limit: 1) {
        status
        jailed
        height
      }
      validatorSigningInfos: validator_signing_infos(order_by: {height: desc}, limit: 1) {
        missedBlocksCounter: missed_blocks_counter
        tombstoned
      }
      validatorCommissions: validator_commissions(order_by: {height: desc}, limit: 1) {
        commission
      }
    }
  }
  slashingParams: slashing_params(order_by: {height: desc}, limit: 1) {
    params
  }
  selfStake: ms_locks(where: {val_addr: {_eq: $address}, staker_addr: {_eq: $delegatorAddress}}, limit: 1) {
    amount
    denom
  }
}

query ValidatorCommission($address: String) {
  validator(where: {validator_info: {operator_address: {_eq: $address}}}) {
    validatorCommissions: validator_commissions(order_by: {height: desc}, limit: 1) {
      commission
    }
  }
}

query ValidatorVotingPowers($address: String) {
  validator(where: {validator_info: {operator_address: {_eq: $address}}}) {
    validatorVotingPowers: validator_voting_powers(offset: 0, limit: 1, order_by: {height: desc}) {
      height
      votingPower: voting_power
    }
    validatorStatuses: validator_statuses(order_by: {height: desc}, limit: 1) {
      status
    }
  }
  stakingPool: staking_pool(order_by: {height: desc}, limit: 1, offset: 0) {
    height
    bonded: bonded_tokens
  }
}

query ValidatorAddress($address: String) {
  validator(where: {validator_info: {operator_address: {_eq: $address}}}) {
    validatorInfo: validator_info {
        operatorAddress: operator_address
        selfDelegateAddress: self_delegate_address
    }
  }
}

query ValidatorPage($address: String!) {
  validator(where: {validator_info: {operator_address: {_eq: $address}}}) {
    validatorInfo: validator_info {
      operatorAddress: operator_address
      selfDelegateAddress: self_delegate_address
      consensusAddress: consensus_address
      maxRate: max_rate
      maxChangeRate: max_change_rate
    }
    validatorDescriptions: validator_descriptions(order_by: {height: desc}, limit: 1) {
      moniker
      identity
      website
      securityContact: security_contact
      details
      avatarUrl: avatar_url
    }
    validatorStatuses: validator_statuses(order_by: {height: desc}, limit: 1) {
      status
      jailed
    }
    validatorSigningInfos: validator_signing_infos(order_by: {height: desc}, limit: 1) {
      missedBlocksCounter: missed_blocks_counter
      tombstoned
    }
    validatorCommissions: validator_commissions(order_by: {height: desc}, limit: 1) {
      commission
    }
    validatorVotingPowers: validator_voting_powers(limit: 1, order_by: {height: desc}) {
      votingPower: voting_power
    }
  }
  validatorDenom: validator_denom(where: {validator: {validator_info: {operator_address: {_eq: $address}}}}) {
    denom
  }
  slashingParams: slashing_params(order_by: {height: desc}, limit: 1) {
    params
  }
  delegations: ms_locks_aggregate(where: {val_addr: {_eq: $address}}) {
    aggregate {
      count
      max {
        amount
      }
    }
  }
  latestBlock: block(limit: 1, order_by: {height: desc}) {
    height
  }
}

query ValidatorProposedBlocks($consensusAddress: String!, $sinceHeight: bigint!, $limit: Int = 10) {
  blocks: block(limit: $limit, order_by: {height: desc}, where: {proposer_address: {_eq: $consensusAddress}}) {
    height
    timestamp
    txs: num_txs
    totalGas: total_gas
  }
  recent: block_aggregate(where: {proposer_address: {_eq: $consensusAddress}, height: {_gt: $sinceHeight}}) {
    aggregate {
      count
    }
  }
}
